repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: detect-private-key
  # check for existence of private keys
  - id: end-of-file-fixer
  - id: trailing-whitespace
  # Trims trailing whitespace.

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ['--write-changes']
    additional_dependencies:
    - 'tomli'