version: 2.1

jobs:
  test-and-upload-python:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              pip install pip tox --upgrade
      - run:
          name: Run tests
          command: tox -v
workflows:
  upload-to-codecov:
    jobs:
      - test-and-upload-python
